# Site settings
title: Hayden Elza
email: hayden.elza@gmail.com
description: >
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas convallis condimentum elit vitae mattis. Suspendisse iaculis dignissim dolor, ac congue ex finibus eget. Ut rhoncus imperdiet orci, non porta dui fringilla ut.
url: "localhost:4000" 
twitter_username: haydenelza
github_username:  haydenelza

# Build settings
markdown: kramdown
permalink: /:title
